### ISSUE TITLE
fabric curved text resolution issue

### ISSUE THREAD

**Issue by hasnat-fabtechsol** [av01d/fabric-brushes#5]
sorry about issue here i don't have any contact of you I tried your solution for curved text and improved it for rendering from json but it add text on 2d context and text will be resterize and when i export canvas it is blurry not like normal fabric text that is crisp can you please help to fix this issue

**Comment by hasnat-fabtechsol** [comment]
https://jsfiddle.net/kingjutt1/fu72dozr/5/

check this fiddle and you can export it to see the difference

**Comment by hasnat-fabtechsol** [comment]
![logo (6)](https://user-images.githubusercontent.com/119284284/234789260-ef99fd05-6f9b-4c1b-9e9d-aa50e3ab0926.png)

**Comment by av01d** [comment]
I know of this issue and I don't know of a solution. Sorry!
